# Physics-Informed Neural Networks for Activity Coefficient Prediction

This notebook presents the development of a physics-informed neural network (PINN) to predict activity coefficients using processed experimental data. By embedding thermodynamic constraints directly into the loss function, we incorporate domain knowledge into the model, ensuring thermodynamic consistency while leveraging a data-driven approach.

## Dependencies

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

from pathlib import Path
from sklearn.model_selection import KFold, train_test_split
from sklearn.preprocessing import MinMaxScaler

## PINN modeling

### Designing the Neural Network Components

Define the architecture of the neural network

In [2]:
torch.manual_seed(42)


class NeuralNetArchitecture(nn.Module):
    def __init__(self, in_dim: int, out_dim: int) -> None:
        super().__init__()
        self.layer_1 = nn.Linear(in_dim, 64)
        self.layer_2 = nn.Linear(64, 32)
        self.layer_3 = nn.Linear(32, 16)
        self.layer_4 = nn.Linear(16, out_dim)

    def forward(self, x):
        x = F.relu(self.layer_1(x))
        x = F.relu(self.layer_2(x))
        x = F.relu(self.layer_3(x))
        x = self.layer_4(x)

        return x

Implement a custom loss function that enforces thermodynamic consistency by embedding the Gibbs-Duhem equation into the standard MSE loss

In [3]:
def gibbs_duhem_loss(
    y_pred: torch.Tensor, y_true: torch.Tensor, X: torch.Tensor, lambda_gd: int = 1
) -> torch.Tensor:
    # MSE error
    mse_loss = torch.mean((y_pred - y_true) ** 2)

    # Gibbs Duhem loss
    gamma1 = y_pred[:, 0]
    dgamma1_dx1 = torch.autograd.grad(
        gamma1,
        X,
        grad_outputs=torch.ones_like(gamma1),
        create_graph=True,
        allow_unused=True,
    )[0][:, 3]

    gamma2 = y_pred[:, 1]
    dgamma2_dx2 = torch.autograd.grad(
        gamma2,
        X,
        grad_outputs=torch.ones_like(gamma2),
        create_graph=True,
        allow_unused=True,
    )[0][:, 6]

    gibbs_duhem_loss = torch.mean((dgamma1_dx1 + dgamma2_dx2) ** 2)

    # Total loss
    loss = mse_loss + gibbs_duhem_loss * lambda_gd
    return loss

### Reading the data

Defining the data path conveniently:

In [4]:
DATA_PATH = Path("../data")

Reading the data into a `pandas.DataFrame`:

In [5]:
data = pd.read_csv(DATA_PATH / "processed" / "toy_problem_input_dataset.csv")

data

          r_1     q_1   x_1     r_2    q_2   x_2        T  gamma_1  gamma_2
0      9.5482   7.976  0.00  5.8486  4.936  1.00  398.839  1.10848  1.00000
1      9.5482   7.976  0.01  5.8486  4.936  0.99  399.213  1.10353  1.00002
2      9.5482   7.976  0.02  5.8486  4.936  0.98  399.590  1.09880  1.00008
3      9.5482   7.976  0.03  5.8486  4.936  0.97  399.971  1.09428  1.00018
4      9.5482   7.976  0.04  5.8486  4.936  0.96  400.355  1.08995  1.00032
...       ...     ...   ...     ...    ...   ...      ...      ...      ...
4035  13.5946  11.216  0.96  3.9243  3.668  0.04  509.434  1.64304  1.00037
4036  13.5946  11.216  0.97  3.9243  3.668  0.03  532.267  1.57456  1.00018
4037  13.5946  11.216  0.98  3.9243  3.668  0.02  568.855  1.47692  1.00006
4038  13.5946  11.216  0.99  3.9243  3.668  0.01  600.617  1.40596  1.00001
4039  13.5946  11.216  1.00  3.9243  3.668  0.00  623.518  1.36162  1.00000

[4040 rows x 9 columns]

Remove rows with NaN values:

In [6]:
data.dropna(inplace=True)
data.reset_index(drop=True, inplace=True)

data

          r_1     q_1   x_1     r_2    q_2   x_2        T  gamma_1  gamma_2
0      9.5482   7.976  0.00  5.8486  4.936  1.00  398.839  1.10848  1.00000
1      9.5482   7.976  0.01  5.8486  4.936  0.99  399.213  1.10353  1.00002
2      9.5482   7.976  0.02  5.8486  4.936  0.98  399.590  1.09880  1.00008
3      9.5482   7.976  0.03  5.8486  4.936  0.97  399.971  1.09428  1.00018
4      9.5482   7.976  0.04  5.8486  4.936  0.96  400.355  1.08995  1.00032
...       ...     ...   ...     ...    ...   ...      ...      ...      ...
4031  13.5946  11.216  0.96  3.9243  3.668  0.04  509.434  1.64304  1.00037
4032  13.5946  11.216  0.97  3.9243  3.668  0.03  532.267  1.57456  1.00018
4033  13.5946  11.216  0.98  3.9243  3.668  0.02  568.855  1.47692  1.00006
4034  13.5946  11.216  0.99  3.9243  3.668  0.01  600.617  1.40596  1.00001
4035  13.5946  11.216  1.00  3.9243  3.668  0.00  623.518  1.36162  1.00000

[4036 rows x 9 columns]

### PINN training

Defining the device and splitting the data into training and test sets

In [7]:
# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

features = data.iloc[:, :-2].values
labels = data.iloc[:, -2:].values

X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.1, random_state=42
)

Defining the cross-validation setup

In [8]:
k_folds = 10
kf = KFold(n_splits=k_folds, shuffle=True, random_state=42)

Specifying training hyperparameters

In [9]:
num_epochs = 10000
learning_rate = 0.001
lambda_gd = 1e-1
patience = 1000

Executing the training loop for the PINN

In [10]:
fold_losses = []
val_losses = []
test_losses = []

for fold, (train_idx, val_idx) in enumerate(kf.split(X_train)):
    print(f"Fold {fold + 1}/{k_folds}")

    # Train-validation split for this fold
    X_train_cv, X_val = X_train[train_idx], X_train[val_idx]
    y_train_cv, y_val = y_train[train_idx], y_train[val_idx]

    # Scale features
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train_cv)
    X_val_scaled = scaler.transform(X_val)
    X_test_scaled = scaler.transform(X_test)

    # Convert to tensors and move to device
    X_train_tensor = torch.tensor(
        X_train_scaled, dtype=torch.float32, requires_grad=True
    ).to(device)
    X_val_tensor = torch.tensor(
        X_val_scaled, dtype=torch.float32, requires_grad=True
    ).to(device)
    X_test_tensor = torch.tensor(
        X_test_scaled, dtype=torch.float32, requires_grad=True
    ).to(device)
    y_train_tensor = torch.tensor(y_train_cv, dtype=torch.float32).to(device)
    y_val_tensor = torch.tensor(y_val, dtype=torch.float32).to(device)
    y_test_tensor = torch.tensor(y_test, dtype=torch.float32).to(device)

    # Model and optimizer
    input_size = X_train_cv.shape[1]
    output_size = 2
    model = NeuralNetArchitecture(input_size, output_size).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

    # Early stopping vars
    best_train_loss = float("inf")
    best_val_loss = float("inf")
    best_model = None
    epochs_no_improve = 0

    # Training loop
    for epoch in range(num_epochs):
        model.train()

        # Forward pass
        outputs = model(X_train_tensor)

        # Loss
        loss = gibbs_duhem_loss(outputs, y_train_tensor, X_train_tensor, lambda_gd)

        # Validation loss
        val_outputs = model(X_val_tensor)
        val_loss = gibbs_duhem_loss(val_outputs, y_val_tensor, X_val_tensor, lambda_gd)

        # Backward propagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Early stopping check
        if val_loss < best_val_loss:
            best_train_loss = loss
            best_val_loss = val_loss
            best_model = model
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1

        if epochs_no_improve >= patience:
            print(f"Early stopping at epoch {epoch + 1}")
            break

        if (epoch + 1) % 20 == 0:
            print(f"[Fold {fold + 1} | Epoch {epoch + 1}]: Training loss -> {loss}")
            print(
                f"[Fold {fold + 1} | Epoch {epoch + 1}]: Validation loss -> {val_loss}"
            )

    # Evaluate test data
    test_outputs = best_model(X_test_tensor)
    test_loss = gibbs_duhem_loss(test_outputs, y_test_tensor, X_test_tensor, lambda_gd)

    # Store best loss for this fold
    fold_losses.append(best_train_loss.item())
    val_losses.append(best_val_loss.item())
    test_losses.append(test_loss.item())

# Print average loss across folds
print(f"Average loss across {k_folds} folds: {np.mean(fold_losses)}")
print(f"Average validation loss across {k_folds} folds: {np.mean(val_losses)}")
print(f"Average test loss across {k_folds} folds: {np.mean(test_losses)}")

Fold 1/10
[Fold 1 | Epoch 20]: Training loss -> 7.341529369354248
[Fold 1 | Epoch 20]: Validation loss -> 6.154910564422607
[Fold 1 | Epoch 40]: Training loss -> 6.7735419273376465
[Fold 1 | Epoch 40]: Validation loss -> 5.614776134490967
[Fold 1 | Epoch 60]: Training loss -> 5.104795455932617
[Fold 1 | Epoch 60]: Validation loss -> 4.053679943084717
[Fold 1 | Epoch 80]: Training loss -> 4.156768798828125
[Fold 1 | Epoch 80]: Validation loss -> 3.310368537902832
[Fold 1 | Epoch 100]: Training loss -> 3.8639817237854004
[Fold 1 | Epoch 100]: Validation loss -> 2.996962308883667
[Fold 1 | Epoch 120]: Training loss -> 3.6446428298950195
[Fold 1 | Epoch 120]: Validation loss -> 2.8017778396606445
[Fold 1 | Epoch 140]: Training loss -> 3.4743762016296387
[Fold 1 | Epoch 140]: Validation loss -> 2.6499648094177246
[Fold 1 | Epoch 160]: Training loss -> 3.35276198387146
[Fold 1 | Epoch 160]: Validation loss -> 2.545811176300049
[Fold 1 | Epoch 180]: Training loss -> 3.266787052154541
[Fold 1 | Epoch 180]: Validation loss -> 2.4731662273406982
[Fold 1 | Epoch 200]: Training loss -> 3.193016767501831
[Fold 1 | Epoch 200]: Validation loss -> 2.4114904403686523
[Fold 1 | Epoch 220]: Training loss -> 3.1251137256622314
[Fold 1 | Epoch 220]: Validation loss -> 2.355588674545288
[Fold 1 | Epoch 240]: Training loss -> 3.063673973083496
[Fold 1 | Epoch 240]: Validation loss -> 2.3057861328125
[Fold 1 | Epoch 260]: Training loss -> 2.9978256225585938
[Fold 1 | Epoch 260]: Validation loss -> 2.253354787826538
[Fold 1 | Epoch 280]: Training loss -> 2.9329988956451416
[Fold 1 | Epoch 280]: Validation loss -> 2.196458578109741
[Fold 1 | Epoch 300]: Training loss -> 2.8679020404815674
[Fold 1 | Epoch 300]: Validation loss -> 2.1401889324188232
[Fold 1 | Epoch 320]: Training loss -> 2.792442560195923
[Fold 1 | Epoch 320]: Validation loss -> 2.0752170085906982
[Fold 1 | Epoch 340]: Training loss -> 2.6968464851379395
[Fold 1 | Epoch 340]: Validation loss -> 1.9888556003570557
[Fold 1 | Epoch 360]: Training loss -> 2.5533370971679688
[Fold 1 | Epoch 360]: Validation loss -> 1.8557480573654175
[Fold 1 | Epoch 380]: Training loss -> 2.401158094406128
[Fold 1 | Epoch 380]: Validation loss -> 1.7147438526153564
[Fold 1 | Epoch 400]: Training loss -> 2.27311635017395
[Fold 1 | Epoch 400]: Validation loss -> 1.606536865234375
[Fold 1 | Epoch 420]: Training loss -> 2.1553826332092285
[Fold 1 | Epoch 420]: Validation loss -> 1.5076475143432617
[Fold 1 | Epoch 440]: Training loss -> 2.0442752838134766
[Fold 1 | Epoch 440]: Validation loss -> 1.426072120666504
[Fold 1 | Epoch 460]: Training loss -> 1.9425992965698242
[Fold 1 | Epoch 460]: Validation loss -> 1.3468154668807983
[Fold 1 | Epoch 480]: Training loss -> 1.8432143926620483
[Fold 1 | Epoch 480]: Validation loss -> 1.2719417810440063
[Fold 1 | Epoch 500]: Training loss -> 1.753693699836731
[Fold 1 | Epoch 500]: Validation loss -> 1.2146313190460205
[Fold 1 | Epoch 520]: Training loss -> 1.6777708530426025
[Fold 1 | Epoch 520]: Validation loss -> 1.1642744541168213
[Fold 1 | Epoch 540]: Training loss -> 1.6087273359298706
[Fold 1 | Epoch 540]: Validation loss -> 1.1232829093933105
[Fold 1 | Epoch 560]: Training loss -> 1.542169451713562
[Fold 1 | Epoch 560]: Validation loss -> 1.0886759757995605
[Fold 1 | Epoch 580]: Training loss -> 1.4797759056091309
[Fold 1 | Epoch 580]: Validation loss -> 1.0602846145629883
[Fold 1 | Epoch 600]: Training loss -> 1.422664999961853
[Fold 1 | Epoch 600]: Validation loss -> 1.034091830253601
[Fold 1 | Epoch 620]: Training loss -> 1.3700337409973145
[Fold 1 | Epoch 620]: Validation loss -> 1.0120952129364014
[Fold 1 | Epoch 640]: Training loss -> 1.3199284076690674
[Fold 1 | Epoch 640]: Validation loss -> 0.9945022463798523
[Fold 1 | Epoch 660]: Training loss -> 1.272554874420166
[Fold 1 | Epoch 660]: Validation loss -> 0.9695728421211243
[Fold 1 | Epoch 680]: Training loss -> 1.2298808097839355
[Fold 1 | Epoch 680]: Validation loss -> 0.9467939734458923
[Fold 1 | Epoch 700]: Training loss -> 1.1905536651611328
[Fold 1 | Epoch 700]: Validation loss -> 0.9295727014541626
[Fold 1 | Epoch 720]: Training loss -> 1.1524370908737183
[Fold 1 | Epoch 720]: Validation loss -> 0.9071089029312134
[Fold 1 | Epoch 740]: Training loss -> 1.1158076524734497
[Fold 1 | Epoch 740]: Validation loss -> 0.8861778378486633
[Fold 1 | Epoch 760]: Training loss -> 1.088144063949585
[Fold 1 | Epoch 760]: Validation loss -> 0.8690394163131714
[Fold 1 | Epoch 780]: Training loss -> 1.0561292171478271
[Fold 1 | Epoch 780]: Validation loss -> 0.8537185192108154
[Fold 1 | Epoch 800]: Training loss -> 1.0317199230194092
[Fold 1 | Epoch 800]: Validation loss -> 0.8378297090530396
[Fold 1 | Epoch 820]: Training loss -> 1.00791597366333
[Fold 1 | Epoch 820]: Validation loss -> 0.8212844133377075
[Fold 1 | Epoch 840]: Training loss -> 0.9793673753738403
[Fold 1 | Epoch 840]: Validation loss -> 0.8069721460342407
[Fold 1 | Epoch 860]: Training loss -> 0.9554076790809631
[Fold 1 | Epoch 860]: Validation loss -> 0.7899326086044312
[Fold 1 | Epoch 880]: Training loss -> 0.9363279342651367
[Fold 1 | Epoch 880]: Validation loss -> 0.7743139863014221
[Fold 1 | Epoch 900]: Training loss -> 0.9169379472732544
[Fold 1 | Epoch 900]: Validation loss -> 0.7590227723121643
[Fold 1 | Epoch 920]: Training loss -> 0.8988110423088074
[Fold 1 | Epoch 920]: Validation loss -> 0.742732048034668
[Fold 1 | Epoch 940]: Training loss -> 0.8791399598121643
[Fold 1 | Epoch 940]: Validation loss -> 0.7284765839576721
[Fold 1 | Epoch 960]: Training loss -> 0.8666473031044006
[Fold 1 | Epoch 960]: Validation loss -> 0.7151533365249634
[Fold 1 | Epoch 980]: Training loss -> 0.8537104725837708
[Fold 1 | Epoch 980]: Validation loss -> 0.7028405070304871
[Fold 1 | Epoch 1000]: Training loss -> 0.8370978832244873
[Fold 1 | Epoch 1000]: Validation loss -> 0.6861388087272644
[Fold 1 | Epoch 1020]: Training loss -> 0.8263497948646545
[Fold 1 | Epoch 1020]: Validation loss -> 0.6770017743110657
[Fold 1 | Epoch 1040]: Training loss -> 0.8151026964187622
[Fold 1 | Epoch 1040]: Validation loss -> 0.6695948839187622
[Fold 1 | Epoch 1060]: Training loss -> 0.7983376383781433
[Fold 1 | Epoch 1060]: Validation loss -> 0.6520187854766846
[Fold 1 | Epoch 1080]: Training loss -> 0.7910452485084534
[Fold 1 | Epoch 1080]: Validation loss -> 0.6492169499397278
[Fold 1 | Epoch 1100]: Training loss -> 0.7779043316841125
[Fold 1 | Epoch 1100]: Validation loss -> 0.6415963768959045
[Fold 1 | Epoch 1120]: Training loss -> 0.7725886702537537
[Fold 1 | Epoch 1120]: Validation loss -> 0.6360117793083191
[Fold 1 | Epoch 1140]: Training loss -> 0.7607319355010986
[Fold 1 | Epoch 1140]: Validation loss -> 0.6237301230430603
[Fold 1 | Epoch 1160]: Training loss -> 0.748841404914856
[Fold 1 | Epoch 1160]: Validation loss -> 0.6176273226737976
[Fold 1 | Epoch 1180]: Training loss -> 0.741647481918335
[Fold 1 | Epoch 1180]: Validation loss -> 0.6098362803459167
[Fold 1 | Epoch 1200]: Training loss -> 0.7271438241004944
[Fold 1 | Epoch 1200]: Validation loss -> 0.5932090878486633
[Fold 1 | Epoch 1220]: Training loss -> 0.7147171497344971
[Fold 1 | Epoch 1220]: Validation loss -> 0.5832455158233643
[Fold 1 | Epoch 1240]: Training loss -> 0.7017647624015808
[Fold 1 | Epoch 1240]: Validation loss -> 0.5751916170120239
[Fold 1 | Epoch 1260]: Training loss -> 0.7021753787994385
[Fold 1 | Epoch 1260]: Validation loss -> 0.5787047743797302
[Fold 1 | Epoch 1280]: Training loss -> 0.6861223578453064
[Fold 1 | Epoch 1280]: Validation loss -> 0.5626519918441772
[Fold 1 | Epoch 1300]: Training loss -> 0.6807850003242493
[Fold 1 | Epoch 1300]: Validation loss -> 0.5587038397789001
[Fold 1 | Epoch 1320]: Training loss -> 0.6680277585983276
[Fold 1 | Epoch 1320]: Validation loss -> 0.5497274398803711
[Fold 1 | Epoch 1340]: Training loss -> 0.6600061058998108
[Fold 1 | Epoch 1340]: Validation loss -> 0.5435134768486023
[Fold 1 | Epoch 1360]: Training loss -> 0.6519798040390015
[Fold 1 | Epoch 1360]: Validation loss -> 0.536926805973053
[Fold 1 | Epoch 1380]: Training loss -> 0.6426376700401306
[Fold 1 | Epoch 1380]: Validation loss -> 0.5281581282615662
[Fold 1 | Epoch 1400]: Training loss -> 0.6394442319869995
[Fold 1 | Epoch 1400]: Validation loss -> 0.524110734462738
[Fold 1 | Epoch 1420]: Training loss -> 0.6300973892211914
[Fold 1 | Epoch 1420]: Validation loss -> 0.5180538296699524
[Fold 1 | Epoch 1440]: Training loss -> 0.6189367175102234
[Fold 1 | Epoch 1440]: Validation loss -> 0.5123347640037537
[Fold 1 | Epoch 1460]: Training loss -> 0.6146891713142395
[Fold 1 | Epoch 1460]: Validation loss -> 0.5096008777618408
[Fold 1 | Epoch 1480]: Training loss -> 0.6045731902122498
[Fold 1 | Epoch 1480]: Validation loss -> 0.5029006600379944
[Fold 1 | Epoch 1500]: Training loss -> 0.5939545631408691
[Fold 1 | Epoch 1500]: Validation loss -> 0.49475815892219543
[Fold 1 | Epoch 1520]: Training loss -> 0.5862824320793152
[Fold 1 | Epoch 1520]: Validation loss -> 0.4892682433128357
[Fold 1 | Epoch 1540]: Training loss -> 0.5854858756065369
[Fold 1 | Epoch 1540]: Validation loss -> 0.488037109375
[Fold 1 | Epoch 1560]: Training loss -> 0.5749450922012329
[Fold 1 | Epoch 1560]: Validation loss -> 0.4802354574203491
[Fold 1 | Epoch 1580]: Training loss -> 0.5673021674156189
[Fold 1 | Epoch 1580]: Validation loss -> 0.4714125692844391
[Fold 1 | Epoch 1600]: Training loss -> 0.5569106340408325
[Fold 1 | Epoch 1600]: Validation loss -> 0.4668847322463989
[Fold 1 | Epoch 1620]: Training loss -> 0.5538779497146606
[Fold 1 | Epoch 1620]: Validation loss -> 0.4608420729637146
[Fold 1 | Epoch 1640]: Training loss -> 0.5424859523773193
[Fold 1 | Epoch 1640]: Validation loss -> 0.4523557424545288
[Fold 1 | Epoch 1660]: Training loss -> 0.5359147191047668
[Fold 1 | Epoch 1660]: Validation loss -> 0.45055240392684937
[Fold 1 | Epoch 1680]: Training loss -> 0.5296742916107178
[Fold 1 | Epoch 1680]: Validation loss -> 0.4452194273471832
[Fold 1 | Epoch 1700]: Training loss -> 0.5312366485595703
[Fold 1 | Epoch 1700]: Validation loss -> 0.45006895065307617
[Fold 1 | Epoch 1720]: Training loss -> 0.519583523273468
[Fold 1 | Epoch 1720]: Validation loss -> 0.44445064663887024
[Fold 1 | Epoch 1740]: Training loss -> 0.518867552280426
[Fold 1 | Epoch 1740]: Validation loss -> 0.440696120262146
[Fold 1 | Epoch 1760]: Training loss -> 0.5119668245315552
[Fold 1 | Epoch 1760]: Validation loss -> 0.4346988797187805
[Fold 1 | Epoch 1780]: Training loss -> 0.5014030933380127
[Fold 1 | Epoch 1780]: Validation loss -> 0.42573463916778564
[Fold 1 | Epoch 1800]: Training loss -> 0.49465882778167725
[Fold 1 | Epoch 1800]: Validation loss -> 0.4211796224117279
[Fold 1 | Epoch 1820]: Training loss -> 0.48859307169914246
[Fold 1 | Epoch 1820]: Validation loss -> 0.4151911437511444
[Fold 1 | Epoch 1840]: Training loss -> 0.48241037130355835
[Fold 1 | Epoch 1840]: Validation loss -> 0.40955010056495667
[Fold 1 | Epoch 1860]: Training loss -> 0.4802246689796448
[Fold 1 | Epoch 1860]: Validation loss -> 0.40905657410621643
[Fold 1 | Epoch 1880]: Training loss -> 0.47787851095199585
[Fold 1 | Epoch 1880]: Validation loss -> 0.4042240381240845
[Fold 1 | Epoch 1900]: Training loss -> 0.4864055812358856
[Fold 1 | Epoch 1900]: Validation loss -> 0.4101460576057434
[Fold 1 | Epoch 1920]: Training loss -> 0.4766952097415924
[Fold 1 | Epoch 1920]: Validation loss -> 0.4077168405056
[Fold 1 | Epoch 1940]: Training loss -> 0.4664880633354187
[Fold 1 | Epoch 1940]: Validation loss -> 0.3962869942188263
[Fold 1 | Epoch 1960]: Training loss -> 0.46222978830337524
[Fold 1 | Epoch 1960]: Validation loss -> 0.3905874788761139
[Fold 1 | Epoch 1980]: Training loss -> 0.45670557022094727
[Fold 1 | Epoch 1980]: Validation loss -> 0.388529896736145
[Fold 1 | Epoch 2000]: Training loss -> 0.45131877064704895
[Fold 1 | Epoch 2000]: Validation loss -> 0.38443994522094727
[Fold 1 | Epoch 2020]: Training loss -> 0.46013444662094116
[Fold 1 | Epoch 2020]: Validation loss -> 0.3904971480369568
[Fold 1 | Epoch 2040]: Training loss -> 0.45394864678382874
[Fold 1 | Epoch 2040]: Validation loss -> 0.38535499572753906
[Fold 1 | Epoch 2060]: Training loss -> 0.44292521476745605
[Fold 1 | Epoch 2060]: Validation loss -> 0.3805603086948395
[Fold 1 | Epoch 2080]: Training loss -> 0.4394264817237854
[Fold 1 | Epoch 2080]: Validation loss -> 0.37688499689102173
[Fold 1 | Epoch 2100]: Training loss -> 0.44370344281196594
[Fold 1 | Epoch 2100]: Validation loss -> 0.37876778841018677
[Fold 1 | Epoch 2120]: Training loss -> 0.43163901567459106
[Fold 1 | Epoch 2120]: Validation loss -> 0.37367337942123413
[Fold 1 | Epoch 2140]: Training loss -> 0.4264132082462311
[Fold 1 | Epoch 2140]: Validation loss -> 0.36694857478141785
[Fold 1 | Epoch 2160]: Training loss -> 0.43542489409446716
[Fold 1 | Epoch 2160]: Validation loss -> 0.3762499690055847
[Fold 1 | Epoch 2180]: Training loss -> 0.4403499662876129
[Fold 1 | Epoch 2180]: Validation loss -> 0.38351088762283325
[Fold 1 | Epoch 2200]: Training loss -> 0.4308463931083679
[Fold 1 | Epoch 2200]: Validation loss -> 0.37994927167892456
[Fold 1 | Epoch 2220]: Training loss -> 0.4231868386268616
[Fold 1 | Epoch 2220]: Validation loss -> 0.36589211225509644
[Fold 1 | Epoch 2240]: Training loss -> 0.41656386852264404
[Fold 1 | Epoch 2240]: Validation loss -> 0.3642772138118744
[Fold 1 | Epoch 2260]: Training loss -> 0.41868361830711365
[Fold 1 | Epoch 2260]: Validation loss -> 0.35941463708877563
[Fold 1 | Epoch 2280]: Training loss -> 0.4140801429748535
[Fold 1 | Epoch 2280]: Validation loss -> 0.3550955653190613
[Fold 1 | Epoch 2300]: Training loss -> 0.40337464213371277
[Fold 1 | Epoch 2300]: Validation loss -> 0.3501156270503998
[Fold 1 | Epoch 2320]: Training loss -> 0.40657615661621094
[Fold 1 | Epoch 2320]: Validation loss -> 0.3457920551300049
[Fold 1 | Epoch 2340]: Training loss -> 0.4159388244152069
[Fold 1 | Epoch 2340]: Validation loss -> 0.3766072988510132
[Fold 1 | Epoch 2360]: Training loss -> 0.4571242928504944
[Fold 1 | Epoch 2360]: Validation loss -> 0.4059774577617645
[Fold 1 | Epoch 2380]: Training loss -> 0.4409216344356537
[Fold 1 | Epoch 2380]: Validation loss -> 0.39758241176605225
[Fold 1 | Epoch 2400]: Training loss -> 0.42120617628097534
[Fold 1 | Epoch 2400]: Validation loss -> 0.36553698778152466
[Fold 1 | Epoch 2420]: Training loss -> 0.40928760170936584
[Fold 1 | Epoch 2420]: Validation loss -> 0.35606229305267334
[Fold 1 | Epoch 2440]: Training loss -> 0.3995666205883026
[Fold 1 | Epoch 2440]: Validation loss -> 0.34331023693084717
[Fold 1 | Epoch 2460]: Training loss -> 0.39137518405914307
[Fold 1 | Epoch 2460]: Validation loss -> 0.34062454104423523
[Fold 1 | Epoch 2480]: Training loss -> 0.38374969363212585
[Fold 1 | Epoch 2480]: Validation loss -> 0.3304328918457031
[Fold 1 | Epoch 2500]: Training loss -> 0.3799813687801361
[Fold 1 | Epoch 2500]: Validation loss -> 0.3258276581764221
[Fold 1 | Epoch 2520]: Training loss -> 0.3777056038379669
[Fold 1 | Epoch 2520]: Validation loss -> 0.32180872559547424
[Fold 1 | Epoch 2540]: Training loss -> 0.3785194456577301
[Fold 1 | Epoch 2540]: Validation loss -> 0.3286029100418091
[Fold 1 | Epoch 2560]: Training loss -> 0.37018489837646484
[Fold 1 | Epoch 2560]: Validation loss -> 0.3301049470901489
[Fold 1 | Epoch 2580]: Training loss -> 0.4087331295013428
[Fold 1 | Epoch 2580]: Validation loss -> 0.3380627930164337
[Fold 1 | Epoch 2600]: Training loss -> 0.369671493768692
[Fold 1 | Epoch 2600]: Validation loss -> 0.33254045248031616
[Fold 1 | Epoch 2620]: Training loss -> 0.36285948753356934
[Fold 1 | Epoch 2620]: Validation loss -> 0.32264575362205505
[Fold 1 | Epoch 2640]: Training loss -> 0.3884294033050537
[Fold 1 | Epoch 2640]: Validation loss -> 0.3247186243534088
[Fold 1 | Epoch 2660]: Training loss -> 0.3594494163990021
[Fold 1 | Epoch 2660]: Validation loss -> 0.3212498128414154
[Fold 1 | Epoch 2680]: Training loss -> 0.3839258849620819
[Fold 1 | Epoch 2680]: Validation loss -> 0.31956881284713745
[Fold 1 | Epoch 2700]: Training loss -> 0.3822474479675293
[Fold 1 | Epoch 2700]: Validation loss -> 0.3145945370197296
[Fold 1 | Epoch 2720]: Training loss -> 0.35531431436538696
[Fold 1 | Epoch 2720]: Validation loss -> 0.3148071765899658
[Fold 1 | Epoch 2740]: Training loss -> 0.379234254360199
[Fold 1 | Epoch 2740]: Validation loss -> 0.3115842342376709
[Fold 1 | Epoch 2760]: Training loss -> 0.3510706126689911
[Fold 1 | Epoch 2760]: Validation loss -> 0.3106869161128998
[Fold 1 | Epoch 2780]: Training loss -> 0.3479955494403839
[Fold 1 | Epoch 2780]: Validation loss -> 0.3079794645309448
[Fold 1 | Epoch 2800]: Training loss -> 0.34638798236846924
[Fold 1 | Epoch 2800]: Validation loss -> 0.30622345209121704
[Fold 1 | Epoch 2820]: Training loss -> 0.34404098987579346
[Fold 1 | Epoch 2820]: Validation loss -> 0.30403268337249756
[Fold 1 | Epoch 2840]: Training loss -> 0.341511994600296
[Fold 1 | Epoch 2840]: Validation loss -> 0.30080774426460266
[Fold 1 | Epoch 2860]: Training loss -> 0.3421880006790161
[Fold 1 | Epoch 2860]: Validation loss -> 0.3027794063091278
[Fold 1 | Epoch 2880]: Training loss -> 0.33715978264808655
[Fold 1 | Epoch 2880]: Validation loss -> 0.2969137132167816
[Fold 1 | Epoch 2900]: Training loss -> 0.3385953903198242
[Fold 1 | Epoch 2900]: Validation loss -> 0.29952412843704224
[Fold 1 | Epoch 2920]: Training loss -> 0.3338472545146942
[Fold 1 | Epoch 2920]: Validation loss -> 0.2930963337421417
[Fold 1 | Epoch 2940]: Training loss -> 0.33237987756729126
[Fold 1 | Epoch 2940]: Validation loss -> 0.292470246553421
[Fold 1 | Epoch 2960]: Training loss -> 0.3317726254463196
[Fold 1 | Epoch 2960]: Validation loss -> 0.29133835434913635
[Fold 1 | Epoch 2980]: Training loss -> 0.328887403011322
[Fold 1 | Epoch 2980]: Validation loss -> 0.28941893577575684
[Fold 1 | Epoch 3000]: Training loss -> 0.32981929183006287
[Fold 1 | Epoch 3000]: Validation loss -> 0.2870841324329376
[Fold 1 | Epoch 3020]: Training loss -> 0.32561302185058594
[Fold 1 | Epoch 3020]: Validation loss -> 0.28522491455078125
[Fold 1 | Epoch 3040]: Training loss -> 0.32549965381622314
[Fold 1 | Epoch 3040]: Validation loss -> 0.2844602167606354
[Fold 1 | Epoch 3060]: Training loss -> 0.32507866621017456
[Fold 1 | Epoch 3060]: Validation loss -> 0.2841726839542389
[Fold 1 | Epoch 3080]: Training loss -> 0.32259708642959595
[Fold 1 | Epoch 3080]: Validation loss -> 0.28402695059776306
[Fold 1 | Epoch 3100]: Training loss -> 0.32056480646133423
[Fold 1 | Epoch 3100]: Validation loss -> 0.2813759446144104
[Fold 1 | Epoch 3120]: Training loss -> 0.3198009431362152
[Fold 1 | Epoch 3120]: Validation loss -> 0.2814455032348633
[Fold 1 | Epoch 3140]: Training loss -> 0.31822898983955383
[Fold 1 | Epoch 3140]: Validation loss -> 0.2803889811038971
[Fold 1 | Epoch 3160]: Training loss -> 0.31795480847358704
[Fold 1 | Epoch 3160]: Validation loss -> 0.2775685787200928
[Fold 1 | Epoch 3180]: Training loss -> 0.3164807856082916
[Fold 1 | Epoch 3180]: Validation loss -> 0.27879175543785095
[Fold 1 | Epoch 3200]: Training loss -> 0.3421160876750946
[Fold 1 | Epoch 3200]: Validation loss -> 0.27561187744140625
[Fold 1 | Epoch 3220]: Training loss -> 0.3136776387691498
[Fold 1 | Epoch 3220]: Validation loss -> 0.27519693970680237
[Fold 1 | Epoch 3240]: Training loss -> 0.3115500509738922
[Fold 1 | Epoch 3240]: Validation loss -> 0.2726380228996277
[Fold 1 | Epoch 3260]: Training loss -> 0.3098970055580139
[Fold 1 | Epoch 3260]: Validation loss -> 0.2715561091899872
[Fold 1 | Epoch 3280]: Training loss -> 0.31113094091415405
[Fold 1 | Epoch 3280]: Validation loss -> 0.2755272686481476
[Fold 1 | Epoch 3300]: Training loss -> 0.3082059919834137
[Fold 1 | Epoch 3300]: Validation loss -> 0.2698516249656677
[Fold 1 | Epoch 3320]: Training loss -> 0.30641433596611023
[Fold 1 | Epoch 3320]: Validation loss -> 0.2692946493625641
[Fold 1 | Epoch 3340]: Training loss -> 0.30512502789497375
[Fold 1 | Epoch 3340]: Validation loss -> 0.2696051001548767